// Code generated by "stringer -type=Event -output events_string.go"; DO NOT EDIT.

package bot

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[EVENT_TICK-0]
	_ = x[EVENT_NOP-1]
	_ = x[EVENT_ENCODING_MENU-2]
	_ = x[EVENT_LOGIN_PROMPT-3]
	_ = x[EVENT_PASSWORD_PROMPT-4]
	_ = x[EVENT_PRESS_CRFL_PROMPT-5]
	_ = x[EVENT_GAME_MENU-6]
	_ = x[EVENT_PROMPT-7]
	_ = x[EVENT_SCORE-8]
	_ = x[EVENT_ATE-9]
	_ = x[EVENT_DRANK-10]
	_ = x[EVENT_NO_SUCH_ITEM-11]
	_ = x[EVENT_WATER_CONTAINER_EMPTY-12]
}

const _Event_name = "EVENT_TICKEVENT_NOPEVENT_ENCODING_MENUEVENT_LOGIN_PROMPTEVENT_PASSWORD_PROMPTEVENT_PRESS_CRFL_PROMPTEVENT_GAME_MENUEVENT_PROMPTEVENT_SCOREEVENT_ATEEVENT_DRANKEVENT_NO_SUCH_ITEMEVENT_WATER_CONTAINER_EMPTY"

var _Event_index = [...]uint8{0, 10, 19, 38, 56, 77, 100, 115, 127, 138, 147, 158, 176, 203}

func (i Event) String() string {
	if i < 0 || i >= Event(len(_Event_index)-1) {
		return "Event(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _Event_name[_Event_index[i]:_Event_index[i+1]]
}
