// Code generated by "stringer -type=State -output states_string.go"; DO NOT EDIT.

package bot

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[STATE_INITIALIZING-0]
	_ = x[STATE_IDLE-1]
	_ = x[STATE_STUCK-2]
	_ = x[STATE_DRINKING-3]
	_ = x[STATE_EATING-4]
	_ = x[STATE_RESTING-5]
}

const _State_name = "STATE_INITIALIZINGSTATE_IDLESTATE_STUCKSTATE_DRINKINGSTATE_EATINGSTATE_RESTING"

var _State_index = [...]uint8{0, 18, 28, 39, 53, 65, 78}

func (i State) String() string {
	if i < 0 || i >= State(len(_State_index)-1) {
		return "State(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _State_name[_State_index[i]:_State_index[i+1]]
}
