// Code generated by "stringer -type=Gender,Class,MoralAlignment,EthicalAlignment,Position -output char_string.go"; DO NOT EDIT.

package char

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[GENDER_MALE-1]
	_ = x[GENDER_FEMALE-2]
}

const _Gender_name = "GENDER_MALEGENDER_FEMALE"

var _Gender_index = [...]uint8{0, 11, 24}

func (i Gender) String() string {
	i -= 1
	if i < 0 || i >= Gender(len(_Gender_index)-1) {
		return "Gender(" + strconv.FormatInt(int64(i+1), 10) + ")"
	}
	return _Gender_name[_Gender_index[i]:_Gender_index[i+1]]
}
func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[CLASS_MERCENARY-1]
	_ = x[CLASS_RANGER-2]
	_ = x[CLASS_KNIGHT_OF_SOLAMNIA-3]
	_ = x[CLASS_THIEF-4]
	_ = x[CLASS_ASSASSIN-5]
	_ = x[CLASS_PRIEST_OF_MISHAKAL-6]
	_ = x[CLASS_PRIEST_OF_MORGION-7]
	_ = x[CLASS_MAGE-8]
}

const _Class_name = "CLASS_MERCENARYCLASS_RANGERCLASS_KNIGHT_OF_SOLAMNIACLASS_THIEFCLASS_ASSASSINCLASS_PRIEST_OF_MISHAKALCLASS_PRIEST_OF_MORGIONCLASS_MAGE"

var _Class_index = [...]uint8{0, 15, 27, 51, 62, 76, 100, 123, 133}

func (i Class) String() string {
	i -= 1
	if i < 0 || i >= Class(len(_Class_index)-1) {
		return "Class(" + strconv.FormatInt(int64(i+1), 10) + ")"
	}
	return _Class_name[_Class_index[i]:_Class_index[i+1]]
}
func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[MORAL_ALIGNMENT_EVIL-1]
	_ = x[MORAL_ALIGNMENT_NEUTRAL-2]
	_ = x[MORAL_ALIGNMENT_GOOD-3]
}

const _MoralAlignment_name = "MORAL_ALIGNMENT_EVILMORAL_ALIGNMENT_NEUTRALMORAL_ALIGNMENT_GOOD"

var _MoralAlignment_index = [...]uint8{0, 20, 43, 63}

func (i MoralAlignment) String() string {
	i -= 1
	if i < 0 || i >= MoralAlignment(len(_MoralAlignment_index)-1) {
		return "MoralAlignment(" + strconv.FormatInt(int64(i+1), 10) + ")"
	}
	return _MoralAlignment_name[_MoralAlignment_index[i]:_MoralAlignment_index[i+1]]
}
func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[ETHICAL_ALIGNMENT_CHAOTIC-1]
	_ = x[ETHICAL_ALIGNMENT_NEUTRAL-2]
	_ = x[ETHICAL_ALIGNMENT_GOOD-3]
}

const _EthicalAlignment_name = "ETHICAL_ALIGNMENT_CHAOTICETHICAL_ALIGNMENT_NEUTRALETHICAL_ALIGNMENT_GOOD"

var _EthicalAlignment_index = [...]uint8{0, 25, 50, 72}

func (i EthicalAlignment) String() string {
	i -= 1
	if i < 0 || i >= EthicalAlignment(len(_EthicalAlignment_index)-1) {
		return "EthicalAlignment(" + strconv.FormatInt(int64(i+1), 10) + ")"
	}
	return _EthicalAlignment_name[_EthicalAlignment_index[i]:_EthicalAlignment_index[i+1]]
}
func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[POSITION_STANDING-1]
	_ = x[POSITION_SITTING-2]
	_ = x[POSITION_RESTING-3]
	_ = x[POSITION_SLEEPING-4]
}

const _Position_name = "POSITION_STANDINGPOSITION_SITTINGPOSITION_RESTINGPOSITION_SLEEPING"

var _Position_index = [...]uint8{0, 17, 33, 49, 66}

func (i Position) String() string {
	i -= 1
	if i < 0 || i >= Position(len(_Position_index)-1) {
		return "Position(" + strconv.FormatInt(int64(i+1), 10) + ")"
	}
	return _Position_name[_Position_index[i]:_Position_index[i+1]]
}
