// Code generated by "stringer -type=Direction -output types_string.go"; DO NOT EDIT.

package atlas

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[DIRECTION_NORTH-0]
	_ = x[DIRECTION_SOUTH-1]
	_ = x[DIRECTION_WEST-2]
	_ = x[DIRECTION_EAST-3]
	_ = x[DIRECTION_UP-4]
	_ = x[DIRECTION_DOWN-5]
	_ = x[DIRECTION_ENTER-6]
	_ = x[DIRECTION_EXIT-7]
}

const _Direction_name = "DIRECTION_NORTHDIRECTION_SOUTHDIRECTION_WESTDIRECTION_EASTDIRECTION_UPDIRECTION_DOWNDIRECTION_ENTERDIRECTION_EXIT"

var _Direction_index = [...]uint8{0, 15, 30, 44, 58, 70, 84, 99, 113}

func (i Direction) String() string {
	if i < 0 || i >= Direction(len(_Direction_index)-1) {
		return "Direction(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _Direction_name[_Direction_index[i]:_Direction_index[i+1]]
}
